// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package db

import (
	"maps"
	"net/netip"

	"tailscale.com/tailcfg"
	"tailscale.com/types/ptr"
)

// Clone makes a deep copy of Data.
// The result aliases no memory with the original.
func (src *Data) Clone() *Data {
	if src == nil {
		return nil
	}
	dst := new(Data)
	*dst = *src
	dst.SnapshotDefaults = src.SnapshotDefaults.Clone()
	if dst.Services != nil {
		dst.Services = map[string]*Service{}
		for k, v := range src.Services {
			if v == nil {
				dst.Services[k] = nil
			} else {
				dst.Services[k] = v.Clone()
			}
		}
	}
	if dst.Images != nil {
		dst.Images = map[ImageRepoName]*ImageRepo{}
		for k, v := range src.Images {
			if v == nil {
				dst.Images[k] = nil
			} else {
				dst.Images[k] = v.Clone()
			}
		}
	}
	if dst.Volumes != nil {
		dst.Volumes = map[string]*Volume{}
		for k, v := range src.Volumes {
			if v == nil {
				dst.Volumes[k] = nil
			} else {
				dst.Volumes[k] = ptr.To(*v)
			}
		}
	}
	if dst.DockerNetworks != nil {
		dst.DockerNetworks = map[string]*DockerNetwork{}
		for k, v := range src.DockerNetworks {
			if v == nil {
				dst.DockerNetworks[k] = nil
			} else {
				dst.DockerNetworks[k] = v.Clone()
			}
		}
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _DataCloneNeedsRegeneration = Data(struct {
	DataVersion      int
	SnapshotDefaults *SnapshotPolicy
	Services         map[string]*Service
	Images           map[ImageRepoName]*ImageRepo
	Volumes          map[string]*Volume
	DockerNetworks   map[string]*DockerNetwork
}{})

// Clone makes a deep copy of Service.
// The result aliases no memory with the original.
func (src *Service) Clone() *Service {
	if src == nil {
		return nil
	}
	dst := new(Service)
	*dst = *src
	dst.SnapshotPolicy = src.SnapshotPolicy.Clone()
	dst.Publish = append(src.Publish[:0:0], src.Publish...)
	if dst.Artifacts != nil {
		dst.Artifacts = map[ArtifactName]*Artifact{}
		for k, v := range src.Artifacts {
			if v == nil {
				dst.Artifacts[k] = nil
			} else {
				dst.Artifacts[k] = v.Clone()
			}
		}
	}
	if dst.SvcNetwork != nil {
		dst.SvcNetwork = ptr.To(*src.SvcNetwork)
	}
	if dst.Macvlan != nil {
		dst.Macvlan = ptr.To(*src.Macvlan)
	}
	dst.TSNet = src.TSNet.Clone()
	dst.VM = src.VM.Clone()
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ServiceCloneNeedsRegeneration = Service(struct {
	Name             string
	ServiceType      ServiceType
	ServiceRoot      string
	ServiceRootZFS   string
	SnapshotPolicy   *SnapshotPolicy
	Generation       int
	LatestGeneration int
	Publish          []string
	Artifacts        ArtifactStore
	SvcNetwork       *SvcNetwork
	Macvlan          *MacvlanNetwork
	TSNet            *TailscaleNetwork
	VM               *VMConfig
}{})

// Clone makes a deep copy of SnapshotPolicy.
// The result aliases no memory with the original.
func (src *SnapshotPolicy) Clone() *SnapshotPolicy {
	if src == nil {
		return nil
	}
	dst := new(SnapshotPolicy)
	*dst = *src
	if dst.Enabled != nil {
		dst.Enabled = ptr.To(*src.Enabled)
	}
	if dst.KeepLast != nil {
		dst.KeepLast = ptr.To(*src.KeepLast)
	}
	dst.Events = append(src.Events[:0:0], src.Events...)
	if dst.Required != nil {
		dst.Required = ptr.To(*src.Required)
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _SnapshotPolicyCloneNeedsRegeneration = SnapshotPolicy(struct {
	Enabled  *bool
	KeepLast *int
	MaxAge   string
	Events   []string
	Required *bool
}{})

// Clone makes a deep copy of Volume.
// The result aliases no memory with the original.
func (src *Volume) Clone() *Volume {
	if src == nil {
		return nil
	}
	dst := new(Volume)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VolumeCloneNeedsRegeneration = Volume(struct {
	Name string
	Src  string
	Path string
	Type string
	Opts string
	Deps string
}{})

// Clone makes a deep copy of ImageRepo.
// The result aliases no memory with the original.
func (src *ImageRepo) Clone() *ImageRepo {
	if src == nil {
		return nil
	}
	dst := new(ImageRepo)
	*dst = *src
	dst.Refs = maps.Clone(src.Refs)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ImageRepoCloneNeedsRegeneration = ImageRepo(struct {
	Refs map[ImageRef]ImageManifest
}{})

// Clone makes a deep copy of Artifact.
// The result aliases no memory with the original.
func (src *Artifact) Clone() *Artifact {
	if src == nil {
		return nil
	}
	dst := new(Artifact)
	*dst = *src
	dst.Refs = maps.Clone(src.Refs)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ArtifactCloneNeedsRegeneration = Artifact(struct {
	Refs map[ArtifactRef]string
}{})

// Clone makes a deep copy of DockerNetwork.
// The result aliases no memory with the original.
func (src *DockerNetwork) Clone() *DockerNetwork {
	if src == nil {
		return nil
	}
	dst := new(DockerNetwork)
	*dst = *src
	if dst.Endpoints != nil {
		dst.Endpoints = map[string]*DockerEndpoint{}
		for k, v := range src.Endpoints {
			if v == nil {
				dst.Endpoints[k] = nil
			} else {
				dst.Endpoints[k] = ptr.To(*v)
			}
		}
	}
	dst.EndpointAddrs = maps.Clone(src.EndpointAddrs)
	if dst.PortMap != nil {
		dst.PortMap = map[string]*EndpointPort{}
		for k, v := range src.PortMap {
			if v == nil {
				dst.PortMap[k] = nil
			} else {
				dst.PortMap[k] = ptr.To(*v)
			}
		}
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _DockerNetworkCloneNeedsRegeneration = DockerNetwork(struct {
	NetworkID     string
	NetNS         string
	IPv4Gateway   netip.Prefix
	IPv4Range     netip.Prefix
	Endpoints     map[string]*DockerEndpoint
	EndpointAddrs map[string]netip.Prefix
	PortMap       map[string]*EndpointPort
}{})

// Clone makes a deep copy of DockerEndpoint.
// The result aliases no memory with the original.
func (src *DockerEndpoint) Clone() *DockerEndpoint {
	if src == nil {
		return nil
	}
	dst := new(DockerEndpoint)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _DockerEndpointCloneNeedsRegeneration = DockerEndpoint(struct {
	EndpointID string
	IPv4       netip.Prefix
}{})

// Clone makes a deep copy of TailscaleNetwork.
// The result aliases no memory with the original.
func (src *TailscaleNetwork) Clone() *TailscaleNetwork {
	if src == nil {
		return nil
	}
	dst := new(TailscaleNetwork)
	*dst = *src
	dst.Tags = append(src.Tags[:0:0], src.Tags...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _TailscaleNetworkCloneNeedsRegeneration = TailscaleNetwork(struct {
	Interface string
	Version   string
	ExitNode  string
	Tags      []string
	StableID  tailcfg.StableNodeID
}{})

// Clone makes a deep copy of EndpointPort.
// The result aliases no memory with the original.
func (src *EndpointPort) Clone() *EndpointPort {
	if src == nil {
		return nil
	}
	dst := new(EndpointPort)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _EndpointPortCloneNeedsRegeneration = EndpointPort(struct {
	EndpointID string
	Port       uint16
}{})

// Clone makes a deep copy of VMConfig.
// The result aliases no memory with the original.
func (src *VMConfig) Clone() *VMConfig {
	if src == nil {
		return nil
	}
	dst := new(VMConfig)
	*dst = *src
	dst.Networks = append(src.Networks[:0:0], src.Networks...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMConfigCloneNeedsRegeneration = VMConfig(struct {
	Runtime     string
	Image       VMImageConfig
	CPUs        int
	MemoryBytes int64
	Disk        VMDiskConfig
	Networks    []VMNetworkConfig
	SSH         VMSSHConfig
	Console     VMConsoleConfig
	Sockets     VMSocketConfig
	PIDFile     string
	SetupState  string
}{})

// Clone makes a deep copy of VMImageConfig.
// The result aliases no memory with the original.
func (src *VMImageConfig) Clone() *VMImageConfig {
	if src == nil {
		return nil
	}
	dst := new(VMImageConfig)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMImageConfigCloneNeedsRegeneration = VMImageConfig(struct {
	Payload string
	Version string
	Digest  string
	Kernel  string
	RootFS  string
}{})

// Clone makes a deep copy of VMDiskConfig.
// The result aliases no memory with the original.
func (src *VMDiskConfig) Clone() *VMDiskConfig {
	if src == nil {
		return nil
	}
	dst := new(VMDiskConfig)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMDiskConfigCloneNeedsRegeneration = VMDiskConfig(struct {
	Backend string
	Bytes   int64
	Path    string
}{})

// Clone makes a deep copy of VMNetworkConfig.
// The result aliases no memory with the original.
func (src *VMNetworkConfig) Clone() *VMNetworkConfig {
	if src == nil {
		return nil
	}
	dst := new(VMNetworkConfig)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMNetworkConfigCloneNeedsRegeneration = VMNetworkConfig(struct {
	Mode      string
	Interface string
	Tap       string
	MAC       string
	IP        netip.Addr
	Parent    string
	VLAN      int
}{})

// Clone makes a deep copy of VMSSHConfig.
// The result aliases no memory with the original.
func (src *VMSSHConfig) Clone() *VMSSHConfig {
	if src == nil {
		return nil
	}
	dst := new(VMSSHConfig)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMSSHConfigCloneNeedsRegeneration = VMSSHConfig(struct {
	User       string
	KeyRef     string
	KnownHosts string
}{})

// Clone makes a deep copy of VMConsoleConfig.
// The result aliases no memory with the original.
func (src *VMConsoleConfig) Clone() *VMConsoleConfig {
	if src == nil {
		return nil
	}
	dst := new(VMConsoleConfig)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMConsoleConfigCloneNeedsRegeneration = VMConsoleConfig(struct {
	SocketPath string
	LogPath    string
}{})

// Clone makes a deep copy of VMSocketConfig.
// The result aliases no memory with the original.
func (src *VMSocketConfig) Clone() *VMSocketConfig {
	if src == nil {
		return nil
	}
	dst := new(VMSocketConfig)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMSocketConfigCloneNeedsRegeneration = VMSocketConfig(struct {
	APISocketPath string
}{})
