// Code generated by tailscale/cmd/viewer; DO NOT EDIT.

package db

import (
	jsonv1 "encoding/json"
	"errors"
	"net/netip"

	jsonv2 "github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"tailscale.com/tailcfg"
	"tailscale.com/types/views"
)

//go:generate go run tailscale.com/cmd/cloner  -clonefunc=false -type=Data,Service,SnapshotPolicy,Volume,ImageRepo,Artifact,DockerNetwork,DockerEndpoint,TailscaleNetwork,EndpointPort,VMConfig,VMImageConfig,VMDiskConfig,VMNetworkConfig,VMSSHConfig,VMConsoleConfig,VMSocketConfig

// View returns a read-only view of Data.
func (p *Data) View() DataView {
	return DataView{ж: p}
}

// DataView provides a read-only view over Data.
//
// Its methods should only be called if `Valid()` returns true.
type DataView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *Data
}

// Valid reports whether v's underlying value is non-nil.
func (v DataView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v DataView) AsStruct() *Data {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v DataView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v DataView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *DataView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x Data
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *DataView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x Data
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// DataVersion is the version of the data format. This is used to determine
// how to parse the data.
func (v DataView) DataVersion() int                     { return v.ж.DataVersion }
func (v DataView) SnapshotDefaults() SnapshotPolicyView { return v.ж.SnapshotDefaults.View() }
func (v DataView) Services() views.MapFn[string, *Service, ServiceView] {
	return views.MapFnOf(v.ж.Services, func(t *Service) ServiceView {
		return t.View()
	})
}
func (v DataView) Images() views.MapFn[ImageRepoName, *ImageRepo, ImageRepoView] {
	return views.MapFnOf(v.ж.Images, func(t *ImageRepo) ImageRepoView {
		return t.View()
	})
}
func (v DataView) Volumes() views.MapFn[string, *Volume, VolumeView] {
	return views.MapFnOf(v.ж.Volumes, func(t *Volume) VolumeView {
		return t.View()
	})
}
func (v DataView) DockerNetworks() views.MapFn[string, *DockerNetwork, DockerNetworkView] {
	return views.MapFnOf(v.ж.DockerNetworks, func(t *DockerNetwork) DockerNetworkView {
		return t.View()
	})
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _DataViewNeedsRegeneration = Data(struct {
	DataVersion      int
	SnapshotDefaults *SnapshotPolicy
	Services         map[string]*Service
	Images           map[ImageRepoName]*ImageRepo
	Volumes          map[string]*Volume
	DockerNetworks   map[string]*DockerNetwork
}{})

// View returns a read-only view of Service.
func (p *Service) View() ServiceView {
	return ServiceView{ж: p}
}

// ServiceView provides a read-only view over Service.
//
// Its methods should only be called if `Valid()` returns true.
type ServiceView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *Service
}

// Valid reports whether v's underlying value is non-nil.
func (v ServiceView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v ServiceView) AsStruct() *Service {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v ServiceView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v ServiceView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *ServiceView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x Service
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *ServiceView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x Service
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// Name is the name of the service.
func (v ServiceView) Name() string             { return v.ж.Name }
func (v ServiceView) ServiceType() ServiceType { return v.ж.ServiceType }

// ServiceRoot is the absolute service root on the catch host.
// Empty means filepath.Join(Store.serviceRoot, Name).
func (v ServiceView) ServiceRoot() string { return v.ж.ServiceRoot }

// ServiceRootZFS is the ZFS dataset name used to resolve ServiceRoot.
// Empty means ServiceRoot is a normal filesystem path or the default root.
func (v ServiceView) ServiceRootZFS() string { return v.ж.ServiceRootZFS }

// SnapshotPolicy overrides catch snapshot defaults for this service.
// Nil means all snapshot settings inherit from server defaults.
func (v ServiceView) SnapshotPolicy() SnapshotPolicyView { return v.ж.SnapshotPolicy.View() }

// Generation is the current generation of the service.
func (v ServiceView) Generation() int { return v.ж.Generation }

// LatestGeneration is the latest generation of the service.
func (v ServiceView) LatestGeneration() int { return v.ж.LatestGeneration }

// Publish lists Docker Compose short-syntax port mappings for the service.
func (v ServiceView) Publish() views.Slice[string] { return views.SliceOf(v.ж.Publish) }

// Artifacts are the artifacts generated for this service.
func (v ServiceView) Artifacts() views.MapFn[ArtifactName, *Artifact, ArtifactView] {
	return views.MapFnOf(v.ж.Artifacts, func(t *Artifact) ArtifactView {
		return t.View()
	})
}
func (v ServiceView) SvcNetwork() views.ValuePointer[SvcNetwork] {
	return views.ValuePointerOf(v.ж.SvcNetwork)
}

func (v ServiceView) Macvlan() views.ValuePointer[MacvlanNetwork] {
	return views.ValuePointerOf(v.ж.Macvlan)
}

func (v ServiceView) TSNet() TailscaleNetworkView { return v.ж.TSNet.View() }
func (v ServiceView) VM() VMConfigView            { return v.ж.VM.View() }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ServiceViewNeedsRegeneration = Service(struct {
	Name             string
	ServiceType      ServiceType
	ServiceRoot      string
	ServiceRootZFS   string
	SnapshotPolicy   *SnapshotPolicy
	Generation       int
	LatestGeneration int
	Publish          []string
	Artifacts        ArtifactStore
	SvcNetwork       *SvcNetwork
	Macvlan          *MacvlanNetwork
	TSNet            *TailscaleNetwork
	VM               *VMConfig
}{})

// View returns a read-only view of SnapshotPolicy.
func (p *SnapshotPolicy) View() SnapshotPolicyView {
	return SnapshotPolicyView{ж: p}
}

// SnapshotPolicyView provides a read-only view over SnapshotPolicy.
//
// Its methods should only be called if `Valid()` returns true.
type SnapshotPolicyView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *SnapshotPolicy
}

// Valid reports whether v's underlying value is non-nil.
func (v SnapshotPolicyView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v SnapshotPolicyView) AsStruct() *SnapshotPolicy {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v SnapshotPolicyView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v SnapshotPolicyView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *SnapshotPolicyView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x SnapshotPolicy
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *SnapshotPolicyView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x SnapshotPolicy
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v SnapshotPolicyView) Enabled() views.ValuePointer[bool] {
	return views.ValuePointerOf(v.ж.Enabled)
}

func (v SnapshotPolicyView) KeepLast() views.ValuePointer[int] {
	return views.ValuePointerOf(v.ж.KeepLast)
}

func (v SnapshotPolicyView) MaxAge() string              { return v.ж.MaxAge }
func (v SnapshotPolicyView) Events() views.Slice[string] { return views.SliceOf(v.ж.Events) }
func (v SnapshotPolicyView) Required() views.ValuePointer[bool] {
	return views.ValuePointerOf(v.ж.Required)
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _SnapshotPolicyViewNeedsRegeneration = SnapshotPolicy(struct {
	Enabled  *bool
	KeepLast *int
	MaxAge   string
	Events   []string
	Required *bool
}{})

// View returns a read-only view of Volume.
func (p *Volume) View() VolumeView {
	return VolumeView{ж: p}
}

// VolumeView provides a read-only view over Volume.
//
// Its methods should only be called if `Valid()` returns true.
type VolumeView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *Volume
}

// Valid reports whether v's underlying value is non-nil.
func (v VolumeView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VolumeView) AsStruct() *Volume {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VolumeView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VolumeView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VolumeView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x Volume
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VolumeView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x Volume
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VolumeView) Name() string { return v.ж.Name }
func (v VolumeView) Src() string  { return v.ж.Src }
func (v VolumeView) Path() string { return v.ж.Path }
func (v VolumeView) Type() string { return v.ж.Type }
func (v VolumeView) Opts() string { return v.ж.Opts }
func (v VolumeView) Deps() string { return v.ж.Deps }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VolumeViewNeedsRegeneration = Volume(struct {
	Name string
	Src  string
	Path string
	Type string
	Opts string
	Deps string
}{})

// View returns a read-only view of ImageRepo.
func (p *ImageRepo) View() ImageRepoView {
	return ImageRepoView{ж: p}
}

// ImageRepoView provides a read-only view over ImageRepo.
//
// Its methods should only be called if `Valid()` returns true.
type ImageRepoView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *ImageRepo
}

// Valid reports whether v's underlying value is non-nil.
func (v ImageRepoView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v ImageRepoView) AsStruct() *ImageRepo {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v ImageRepoView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v ImageRepoView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *ImageRepoView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x ImageRepo
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *ImageRepoView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x ImageRepo
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v ImageRepoView) Refs() views.Map[ImageRef, ImageManifest] { return views.MapOf(v.ж.Refs) }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ImageRepoViewNeedsRegeneration = ImageRepo(struct {
	Refs map[ImageRef]ImageManifest
}{})

// View returns a read-only view of Artifact.
func (p *Artifact) View() ArtifactView {
	return ArtifactView{ж: p}
}

// ArtifactView provides a read-only view over Artifact.
//
// Its methods should only be called if `Valid()` returns true.
type ArtifactView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *Artifact
}

// Valid reports whether v's underlying value is non-nil.
func (v ArtifactView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v ArtifactView) AsStruct() *Artifact {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v ArtifactView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v ArtifactView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *ArtifactView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x Artifact
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *ArtifactView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x Artifact
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// path on disk
func (v ArtifactView) Refs() views.Map[ArtifactRef, string] { return views.MapOf(v.ж.Refs) }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _ArtifactViewNeedsRegeneration = Artifact(struct {
	Refs map[ArtifactRef]string
}{})

// View returns a read-only view of DockerNetwork.
func (p *DockerNetwork) View() DockerNetworkView {
	return DockerNetworkView{ж: p}
}

// DockerNetworkView provides a read-only view over DockerNetwork.
//
// Its methods should only be called if `Valid()` returns true.
type DockerNetworkView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *DockerNetwork
}

// Valid reports whether v's underlying value is non-nil.
func (v DockerNetworkView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v DockerNetworkView) AsStruct() *DockerNetwork {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v DockerNetworkView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v DockerNetworkView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *DockerNetworkView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x DockerNetwork
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *DockerNetworkView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x DockerNetwork
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v DockerNetworkView) NetworkID() string         { return v.ж.NetworkID }
func (v DockerNetworkView) NetNS() string             { return v.ж.NetNS }
func (v DockerNetworkView) IPv4Gateway() netip.Prefix { return v.ж.IPv4Gateway }
func (v DockerNetworkView) IPv4Range() netip.Prefix   { return v.ж.IPv4Range }
func (v DockerNetworkView) Endpoints() views.MapFn[string, *DockerEndpoint, DockerEndpointView] {
	return views.MapFnOf(v.ж.Endpoints, func(t *DockerEndpoint) DockerEndpointView {
		return t.View()
	})
}

// Deprecated: use Endpoints instead.
func (v DockerNetworkView) EndpointAddrs() views.Map[string, netip.Prefix] {
	return views.MapOf(v.ж.EndpointAddrs)
}

// key is "proto/hostport"
func (v DockerNetworkView) PortMap() views.MapFn[string, *EndpointPort, EndpointPortView] {
	return views.MapFnOf(v.ж.PortMap, func(t *EndpointPort) EndpointPortView {
		return t.View()
	})
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _DockerNetworkViewNeedsRegeneration = DockerNetwork(struct {
	NetworkID     string
	NetNS         string
	IPv4Gateway   netip.Prefix
	IPv4Range     netip.Prefix
	Endpoints     map[string]*DockerEndpoint
	EndpointAddrs map[string]netip.Prefix
	PortMap       map[string]*EndpointPort
}{})

// View returns a read-only view of DockerEndpoint.
func (p *DockerEndpoint) View() DockerEndpointView {
	return DockerEndpointView{ж: p}
}

// DockerEndpointView provides a read-only view over DockerEndpoint.
//
// Its methods should only be called if `Valid()` returns true.
type DockerEndpointView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *DockerEndpoint
}

// Valid reports whether v's underlying value is non-nil.
func (v DockerEndpointView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v DockerEndpointView) AsStruct() *DockerEndpoint {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v DockerEndpointView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v DockerEndpointView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *DockerEndpointView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x DockerEndpoint
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *DockerEndpointView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x DockerEndpoint
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v DockerEndpointView) EndpointID() string { return v.ж.EndpointID }
func (v DockerEndpointView) IPv4() netip.Prefix { return v.ж.IPv4 }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _DockerEndpointViewNeedsRegeneration = DockerEndpoint(struct {
	EndpointID string
	IPv4       netip.Prefix
}{})

// View returns a read-only view of TailscaleNetwork.
func (p *TailscaleNetwork) View() TailscaleNetworkView {
	return TailscaleNetworkView{ж: p}
}

// TailscaleNetworkView provides a read-only view over TailscaleNetwork.
//
// Its methods should only be called if `Valid()` returns true.
type TailscaleNetworkView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *TailscaleNetwork
}

// Valid reports whether v's underlying value is non-nil.
func (v TailscaleNetworkView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v TailscaleNetworkView) AsStruct() *TailscaleNetwork {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v TailscaleNetworkView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v TailscaleNetworkView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *TailscaleNetworkView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x TailscaleNetwork
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *TailscaleNetworkView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x TailscaleNetwork
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v TailscaleNetworkView) Interface() string              { return v.ж.Interface }
func (v TailscaleNetworkView) Version() string                { return v.ж.Version }
func (v TailscaleNetworkView) ExitNode() string               { return v.ж.ExitNode }
func (v TailscaleNetworkView) Tags() views.Slice[string]      { return views.SliceOf(v.ж.Tags) }
func (v TailscaleNetworkView) StableID() tailcfg.StableNodeID { return v.ж.StableID }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _TailscaleNetworkViewNeedsRegeneration = TailscaleNetwork(struct {
	Interface string
	Version   string
	ExitNode  string
	Tags      []string
	StableID  tailcfg.StableNodeID
}{})

// View returns a read-only view of EndpointPort.
func (p *EndpointPort) View() EndpointPortView {
	return EndpointPortView{ж: p}
}

// EndpointPortView provides a read-only view over EndpointPort.
//
// Its methods should only be called if `Valid()` returns true.
type EndpointPortView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *EndpointPort
}

// Valid reports whether v's underlying value is non-nil.
func (v EndpointPortView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v EndpointPortView) AsStruct() *EndpointPort {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v EndpointPortView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v EndpointPortView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *EndpointPortView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x EndpointPort
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *EndpointPortView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x EndpointPort
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v EndpointPortView) EndpointID() string { return v.ж.EndpointID }
func (v EndpointPortView) Port() uint16       { return v.ж.Port }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _EndpointPortViewNeedsRegeneration = EndpointPort(struct {
	EndpointID string
	Port       uint16
}{})

// View returns a read-only view of VMConfig.
func (p *VMConfig) View() VMConfigView {
	return VMConfigView{ж: p}
}

// VMConfigView provides a read-only view over VMConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMConfigView) AsStruct() *VMConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMConfigView) Runtime() string                        { return v.ж.Runtime }
func (v VMConfigView) Image() VMImageConfig                   { return v.ж.Image }
func (v VMConfigView) CPUs() int                              { return v.ж.CPUs }
func (v VMConfigView) MemoryBytes() int64                     { return v.ж.MemoryBytes }
func (v VMConfigView) Disk() VMDiskConfig                     { return v.ж.Disk }
func (v VMConfigView) Networks() views.Slice[VMNetworkConfig] { return views.SliceOf(v.ж.Networks) }
func (v VMConfigView) SSH() VMSSHConfig                       { return v.ж.SSH }
func (v VMConfigView) Console() VMConsoleConfig               { return v.ж.Console }
func (v VMConfigView) Sockets() VMSocketConfig                { return v.ж.Sockets }
func (v VMConfigView) PIDFile() string                        { return v.ж.PIDFile }
func (v VMConfigView) SetupState() string                     { return v.ж.SetupState }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMConfigViewNeedsRegeneration = VMConfig(struct {
	Runtime     string
	Image       VMImageConfig
	CPUs        int
	MemoryBytes int64
	Disk        VMDiskConfig
	Networks    []VMNetworkConfig
	SSH         VMSSHConfig
	Console     VMConsoleConfig
	Sockets     VMSocketConfig
	PIDFile     string
	SetupState  string
}{})

// View returns a read-only view of VMImageConfig.
func (p *VMImageConfig) View() VMImageConfigView {
	return VMImageConfigView{ж: p}
}

// VMImageConfigView provides a read-only view over VMImageConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMImageConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMImageConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMImageConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMImageConfigView) AsStruct() *VMImageConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMImageConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMImageConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMImageConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMImageConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMImageConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMImageConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMImageConfigView) Payload() string         { return v.ж.Payload }
func (v VMImageConfigView) Version() string         { return v.ж.Version }
func (v VMImageConfigView) Digest() string          { return v.ж.Digest }
func (v VMImageConfigView) Kernel() string          { return v.ж.Kernel }
func (v VMImageConfigView) RootFS() string          { return v.ж.RootFS }
func (v VMImageConfigView) Distro() string          { return v.ж.Distro }
func (v VMImageConfigView) DistroVersion() string   { return v.ж.DistroVersion }
func (v VMImageConfigView) DefaultUser() string     { return v.ж.DefaultUser }
func (v VMImageConfigView) GuestSystemInit() string { return v.ж.GuestSystemInit }
func (v VMImageConfigView) MetadataDriver() string  { return v.ж.MetadataDriver }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMImageConfigViewNeedsRegeneration = VMImageConfig(struct {
	Payload         string
	Version         string
	Digest          string
	Kernel          string
	RootFS          string
	Distro          string
	DistroVersion   string
	DefaultUser     string
	GuestSystemInit string
	MetadataDriver  string
}{})

// View returns a read-only view of VMDiskConfig.
func (p *VMDiskConfig) View() VMDiskConfigView {
	return VMDiskConfigView{ж: p}
}

// VMDiskConfigView provides a read-only view over VMDiskConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMDiskConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMDiskConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMDiskConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMDiskConfigView) AsStruct() *VMDiskConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMDiskConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMDiskConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMDiskConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMDiskConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMDiskConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMDiskConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMDiskConfigView) Backend() string { return v.ж.Backend }
func (v VMDiskConfigView) Bytes() int64    { return v.ж.Bytes }
func (v VMDiskConfigView) Path() string    { return v.ж.Path }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMDiskConfigViewNeedsRegeneration = VMDiskConfig(struct {
	Backend string
	Bytes   int64
	Path    string
}{})

// View returns a read-only view of VMNetworkConfig.
func (p *VMNetworkConfig) View() VMNetworkConfigView {
	return VMNetworkConfigView{ж: p}
}

// VMNetworkConfigView provides a read-only view over VMNetworkConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMNetworkConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMNetworkConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMNetworkConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMNetworkConfigView) AsStruct() *VMNetworkConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMNetworkConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMNetworkConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMNetworkConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMNetworkConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMNetworkConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMNetworkConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMNetworkConfigView) Mode() string      { return v.ж.Mode }
func (v VMNetworkConfigView) Interface() string { return v.ж.Interface }
func (v VMNetworkConfigView) Tap() string       { return v.ж.Tap }
func (v VMNetworkConfigView) MAC() string       { return v.ж.MAC }
func (v VMNetworkConfigView) IP() netip.Addr    { return v.ж.IP }
func (v VMNetworkConfigView) Parent() string    { return v.ж.Parent }
func (v VMNetworkConfigView) VLAN() int         { return v.ж.VLAN }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMNetworkConfigViewNeedsRegeneration = VMNetworkConfig(struct {
	Mode      string
	Interface string
	Tap       string
	MAC       string
	IP        netip.Addr
	Parent    string
	VLAN      int
}{})

// View returns a read-only view of VMSSHConfig.
func (p *VMSSHConfig) View() VMSSHConfigView {
	return VMSSHConfigView{ж: p}
}

// VMSSHConfigView provides a read-only view over VMSSHConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMSSHConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMSSHConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMSSHConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMSSHConfigView) AsStruct() *VMSSHConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMSSHConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMSSHConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMSSHConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMSSHConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMSSHConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMSSHConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMSSHConfigView) User() string       { return v.ж.User }
func (v VMSSHConfigView) KeyRef() string     { return v.ж.KeyRef }
func (v VMSSHConfigView) KnownHosts() string { return v.ж.KnownHosts }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMSSHConfigViewNeedsRegeneration = VMSSHConfig(struct {
	User       string
	KeyRef     string
	KnownHosts string
}{})

// View returns a read-only view of VMConsoleConfig.
func (p *VMConsoleConfig) View() VMConsoleConfigView {
	return VMConsoleConfigView{ж: p}
}

// VMConsoleConfigView provides a read-only view over VMConsoleConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMConsoleConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMConsoleConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMConsoleConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMConsoleConfigView) AsStruct() *VMConsoleConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMConsoleConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMConsoleConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMConsoleConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMConsoleConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMConsoleConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMConsoleConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMConsoleConfigView) SocketPath() string { return v.ж.SocketPath }
func (v VMConsoleConfigView) LogPath() string    { return v.ж.LogPath }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMConsoleConfigViewNeedsRegeneration = VMConsoleConfig(struct {
	SocketPath string
	LogPath    string
}{})

// View returns a read-only view of VMSocketConfig.
func (p *VMSocketConfig) View() VMSocketConfigView {
	return VMSocketConfigView{ж: p}
}

// VMSocketConfigView provides a read-only view over VMSocketConfig.
//
// Its methods should only be called if `Valid()` returns true.
type VMSocketConfigView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *VMSocketConfig
}

// Valid reports whether v's underlying value is non-nil.
func (v VMSocketConfigView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v VMSocketConfigView) AsStruct() *VMSocketConfig {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v VMSocketConfigView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v VMSocketConfigView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *VMSocketConfigView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x VMSocketConfig
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *VMSocketConfigView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x VMSocketConfig
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v VMSocketConfigView) APISocketPath() string   { return v.ж.APISocketPath }
func (v VMSocketConfigView) VsockSocketPath() string { return v.ж.VsockSocketPath }
func (v VMSocketConfigView) VsockGuestCID() uint32   { return v.ж.VsockGuestCID }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _VMSocketConfigViewNeedsRegeneration = VMSocketConfig(struct {
	APISocketPath   string
	VsockSocketPath string
	VsockGuestCID   uint32
}{})
